# Generated by Django 5.1 on 2024-08-23 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=255)),
                ('apellidos', models.CharField(max_length=255)),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('confirm_password', models.CharField(max_length=255)),
                ('codigo_empresa', models.CharField(max_length=255)),
                ('ciudad', models.CharField(max_length=255)),
                ('cargo', models.CharField(choices=[('desarrollador', 'Desarrollador'), ('diseñador', 'Diseñador'), ('analista', 'Analista')], max_length=50)),
            ],
        ),
    ]
