# Generated by Django 5.1 on 2024-08-24 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seguros', '0002_alter_registro_cedula_alter_registro_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ci', models.CharField(max_length=20, unique=True)),
                ('licencia', models.CharField(choices=[('tipo1', 'Tipo 1'), ('tipo2', 'Tipo 2'), ('tipo3', 'Tipo 3')], max_length=10)),
                ('pago_servicio', models.FileField(blank=True, null=True, upload_to='pagos_servicios')),
                ('ci_conyugue', models.CharField(blank=True, max_length=20, null=True)),
                ('disolucion_conyugal', models.CharField(blank=True, max_length=255, null=True)),
                ('formulario_vinculacion', models.FileField(blank=True, null=True, upload_to='clientes')),
            ],
        ),
    ]
