# Generated by Django 5.1 on 2024-08-24 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seguros', '0003_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ci_representante', models.CharField(max_length=20, unique=True)),
                ('ruc', models.CharField(max_length=13, unique=True)),
                ('constitucion', models.CharField(max_length=255)),
                ('nomina', models.FileField(upload_to='nominas_socios')),
            ],
        ),
    ]
