# Generated by Django 5.1 on 2024-08-24 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seguros', '0004_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostVenta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('poliza', models.FileField(upload_to='polizas_digitales/')),
                ('plan_pago', models.CharField(choices=[('plan1', 'Plan Básico'), ('plan2', 'Plan Estándar'), ('plan3', 'Plan Premium')], max_length=10)),
                ('novedades', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
