# Generated by Django 5.1 on 2024-08-24 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seguros', '0005_postventa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_nacimiento', models.DateField()),
                ('estado_civil', models.CharField(choices=[('soltero', 'Soltero'), ('casado', 'Casado'), ('divorciado', 'Divorciado'), ('viudo', 'Viudo')], max_length=10)),
                ('ocupacion', models.CharField(max_length=255)),
                ('observaciones', models.TextField()),
            ],
        ),
    ]
